name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build project
        run: |
          corepack enable
          pnpm install --no-frozen-lockfile
          pnpm -w run docs:build
          cd packages/.vitepress/dist && zip -rq ../../../build.zip .

      - name: Upload to Zeabur
        env:
          PROJECT_ID: 66739d4d820ee0109ea8d472
          SERVICE_ID: 66739ded820ee0109ea8d48f
          ENVIRONMENT_ID: 66739d4db749b5d1f1c96e80
          API_TOKEN: ${{ secrets.ZEABUR_TOKEN }}
        run: |
          curl --request POST \
            --url https://gateway.zeabur.com/projects/${{ env.PROJECT_ID }}/services/${{ env.SERVICE_ID }}/deploy \
            --header "Authorization: Bearer ${{ env.API_TOKEN }}" \
            --form "code=@build.zip" \
            --form "environment=${{ env.ENVIRONMENT_ID }}"
